# general configuration
url:
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "images/virus.png"
  # author will appear under the avatar (optional)
  author: "Counting Covid-19"
  # tagline will appear under the title (optional)
  tagline: "A series of interactive<br>data dashboards"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
